### ISSUE TITLE
Old code base.

### ISSUE THREAD

**Issue by kenthinson** [pgeorgi/edk2#2]
Hello! I am looking at this project looks really cool. Can you merge in the changes from upstream? It looks like most of the code in this repo is 1-2 years old. Thanks!

**Comment by gabemaiberger** [comment]
I agree! The code base should be updated to the most recent version!

**Comment by NHellFire** [comment]
Here's my attempt at updating: https://github.com/NHellFire/coreboot-edk2

I built on Ubuntu 17.04 using coreboot's toolchain:
```
$ make -C BaseTools
$ . edksetup.sh
Edit Conf/tools_def.txt, set *_GCC5_*_MAKE_PATH to make
$ export GCC5_BIN=/path/to/coreboot/util/crossgcc/xgcc/bin/x86_64-elf-
$ build -t GCC5 -a IA32 -p corebootPkg/corebootPkg.dsc
$ build -t GCC5 -a X64 -p corebootPkg/corebootPkg.dsc
```

32bit builds fine, but 64bit fails the same as #1 

But in qemu I don't make it to the EFI shell, it hangs for a while then eventually I get an assert failure. I probably need to go through the changes to OvmfPkg since it was copied to corebootPkg and merge them. So far all I've done is merge upstream's changes in and add the missing libraries to get it to build.

**Comment by pgeorgi** [comment]
Use tianocore's CorebootPayloadPkg.
